# Generated by Django 5.2.1 on 2025-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, help_text="Indica se l'utente è iscritto alla newsletter."),
        ),
    ]
