# Generated by Django 5.2.4 on 2025-07-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='Subscribe to the newsletter'),
        ),
    ]
