# Generated by Django 5.2.1 on 2025-07-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
