# Generated by Django 5.2.1 on 2025-07-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('location', models.CharField(max_length=300)),
                ('provincia', models.CharField(blank=True, choices=[('Agrigento', 'Agrigento (AG)'), ('Alessandria', 'Alessandria (AL)'), ('Ancona', 'Ancona (AN)'), ('Aosta', 'Aosta (AO)'), ('Arezzo', 'Arezzo (AR)'), ('Ascoli Piceno', 'Ascoli Piceno (AP)'), ('Asti', 'Asti (AT)'), ('Avellino', 'Avellino (AV)'), ('Bari', 'Bari (BA)'), ('Barletta-Andria-Trani', 'Barletta-Andria-Trani (BT)'), ('Belluno', 'Belluno (BL)'), ('Benevento', 'Benevento (BN)'), ('Bergamo', 'Bergamo (BG)'), ('Biella', 'Biella (BI)'), ('Bologna', 'Bologna (BO)'), ('Brindisi', 'Brindisi (BR)'), ('Cagliari', 'Cagliari (CA)'), ('Caltanissetta', 'Caltanissetta (CL)'), ('Campobasso', 'Campobasso (CB)'), ('Caserta', 'Caserta (CE)'), ('Catania', 'Catania (CT)'), ('Catanzaro', 'Catanzaro (CZ)'), ('Chieti', 'Chieti (CH)'), ('Como', 'Como (CO)'), ('Cosenza', 'Cosenza (CS)'), ('Cremona', 'Cremona (CR)'), ('Crotone', 'Crotone (KR)'), ('Cuneo', 'Cuneo (CN)'), ('Enna', 'Enna (EN)'), ('Ferrara', 'Ferrara (FE)'), ('Firenze', 'Firenze (FI)'), ('Foggia', 'Foggia (FG)'), ('Forlì-Cesena', 'Forlì-Cesena (FC)'), ('Frosinone', 'Frosinone (FR)'), ('Genova', 'Genova (GE)'), ('Gorizia', 'Gorizia (GO)'), ('Grosseto', 'Grosseto (GR)'), ('Imperia', 'Imperia (IM)'), ('Isernia', 'Isernia (IS)'), ('La Spezia', 'La Spezia (SP)'), ("L'Aquila", "L'Aquila (AQ)"), ('Latina', 'Latina (LT)'), ('Lecce', 'Lecce (LE)'), ('Lecco', 'Lecco (LC)'), ('Livorno', 'Livorno (LI)'), ('Lodi', 'Lodi (LO)'), ('Lucca', 'Lucca (LU)'), ('Macerata', 'Macerata (MC)'), ('Mantova', 'Mantova (MN)'), ('Massa-Carrara', 'Massa-Carrara (MS)'), ('Matera', 'Matera (MT)'), ('Messina', 'Messina (ME)'), ('Milano', 'Milano (MI)'), ('Modena', 'Modena (MO)'), ('Monza e della Brianza', 'Monza e della Brianza (MB)'), ('Napoli', 'Napoli (NA)'), ('Novara', 'Novara (NO)'), ('Nuoro', 'Nuoro (NU)'), ('Oristano', 'Oristano (OR)'), ('Padova', 'Padova (PD)'), ('Palermo', 'Palermo (PA)'), ('Parma', 'Parma (PR)'), ('Pavia', 'Pavia (PV)'), ('Perugia', 'Perugia (PG)'), ('Pesaro e Urbino', 'Pesaro e Urbino (PU)'), ('Pescara', 'Pescara (PE)'), ('Piacenza', 'Piacenza (PC)'), ('Pisa', 'Pisa (PI)'), ('Pistoia', 'Pistoia (PT)'), ('Pordenone', 'Pordenone (PN)'), ('Potenza', 'Potenza (PZ)'), ('Prato', 'Prato (PO)'), ('Ragusa', 'Ragusa (RG)'), ('Ravenna', 'Ravenna (RA)'), ('Reggio Calabria', 'Reggio Calabria (RC)'), ('Reggio Emilia', 'Reggio Emilia (RE)'), ('Rieti', 'Rieti (RI)'), ('Rimini', 'Rimini (RN)'), ('Roma', 'Roma (RM)'), ('Rovigo', 'Rovigo (RO)'), ('Salerno', 'Salerno (SA)'), ('Sassari', 'Sassari (SS)'), ('Savona', 'Savona (SV)'), ('Siena', 'Siena (SI)'), ('Siracusa', 'Siracusa (SR)'), ('Sondrio', 'Sondrio (SO)'), ('Taranto', 'Taranto (TA)'), ('Teramo', 'Teramo (TE)'), ('Terni', 'Terni (TR)'), ('Torino', 'Torino (TO)'), ('Trapani', 'Trapani (TP)'), ('Trento', 'Trento (TN)'), ('Treviso', 'Treviso (TV)'), ('Trieste', 'Trieste (TS)'), ('Udine', 'Udine (UD)'), ('Varese', 'Varese (VA)'), ('Venezia', 'Venezia (VE)'), ('Verbano-Cusio-Ossola', 'Verbano-Cusio-Ossola (VB)'), ('Vercelli', 'Vercelli (VC)'), ('Verona', 'Verona (VR)'), ('Vibo Valentia', 'Vibo Valentia (VV)'), ('Vicenza', 'Vicenza (VI)'), ('Viterbo', 'Viterbo (VT)')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('musica', 'Musica e Concerti'), ('arte', 'Arte e Cultura'), ('teatro', 'Teatro e Spettacoli'), ('cinema', 'Cinema'), ('sport', 'Sport e Fitness'), ('corsi', 'Corsi e Workshop'), ('conferenze', 'Conferenze e Seminari'), ('fiere', 'Fiere e Mercatini'), ('sagre', 'Sagre e Gastronomia'), ('bambini', 'Eventi per Bambini e Famiglie'), ('tecnologia', 'Tecnologia e Innovazione'), ('volontariato', 'Volontariato e Sociale'), ('moda', 'Moda e Lifestyle'), ('natura', 'Natura e Outdoor'), ('danza', 'Danza e Ballo'), ('religione', 'Religione e Spiritualità'), ('business', 'Networking e Business'), ('festival', 'Festival'), ('mostre', 'Mostre'), ('altro', 'Altro')], max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'user_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='events.event')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'regular'}, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
